name: FalcoManager
description: falco manager

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6

  cupertino_icons: ^1.0.2
  supercharged: ^2.1.1
  chopper: ^4.0.1
  json_annotation: ^4.4.0
  flutter_holo_date_picker: ^1.0.3
  intl: ^0.17.0
  bottom_navy_bar: ^6.0.0
  provider: ^6.0.3
  google_fonts: ^3.0.1
  dropdown_button2: ^1.5.2
  syncfusion_flutter_datepicker: ^20.1.5
  uuid: ^3.0.6
  msix: ^2.8.13
  fluent_ui: ^3.10.0
  dotted_border: ^2.0.0
  side_sheet: ^1.0.1
  adaptive_scrollbar: ^2.1.2
  font_awesome_flutter: ^10.1.0
  device_preview: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.7
  chopper_generator: ^4.0.5
  json_serializable: ^6.1.4
  swagger_dart_code_generator: ^2.4.6
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true